/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../app/util/not-found';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
var renderType_PageNotFoundComponent_Host:import0.RenderComponentType = (null as any);
class _View_PageNotFoundComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _PageNotFoundComponent_0_4:import3.PageNotFoundComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PageNotFoundComponent_Host0,renderType_PageNotFoundComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_PageNotFoundComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._PageNotFoundComponent_0_4 = new import3.PageNotFoundComponent();
    this._appEl_0.initComponent(this._PageNotFoundComponent_0_4,[],compView_0);
    compView_0.create(this._PageNotFoundComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.PageNotFoundComponent) && (0 === requestNodeIndex))) { return this._PageNotFoundComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_PageNotFoundComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_PageNotFoundComponent_Host === (null as any))) { (renderType_PageNotFoundComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_PageNotFoundComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const PageNotFoundComponentNgFactory:import9.ComponentFactory<import3.PageNotFoundComponent> = new import9.ComponentFactory<import3.PageNotFoundComponent>('ng-component',viewFactory_PageNotFoundComponent_Host0,import3.PageNotFoundComponent);
const styles_PageNotFoundComponent:any[] = [];
var renderType_PageNotFoundComponent:import0.RenderComponentType = (null as any);
class _View_PageNotFoundComponent0 extends import1.AppView<import3.PageNotFoundComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PageNotFoundComponent0,renderType_PageNotFoundComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','page-not-found container');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','card card-outline-primary text-xs-center');
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','card-header');
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h3',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'404, page not found.',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','card-block');
    this._text_11 = this.renderer.createText(this._el_10,'\n\n      ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'p',(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'Y U do dis? plz don\'t do. plz.',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n      ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_10,'p',(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'Y U no just use good?',(null as any));
    this._text_17 = this.renderer.createText(this._el_10,'\n      ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_10,'p',(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'Use good plz',(null as any));
    this._text_20 = this.renderer.createText(this._el_10,'\n    ',(null as any));
    this._text_21 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22
    ]
    ,[],[]);
    return (null as any);
  }
}
export function viewFactory_PageNotFoundComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.PageNotFoundComponent> {
  if ((renderType_PageNotFoundComponent === (null as any))) { (renderType_PageNotFoundComponent = viewUtils.createRenderComponentType('C:/Git/projects/ForeFront/client/app/util/page-not-found.html',0,import8.ViewEncapsulation.None,styles_PageNotFoundComponent,{})); }
  return new _View_PageNotFoundComponent0(viewUtils,parentInjector,declarationEl);
}