/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../app/line-height/typography-thinger.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/forms/src/directives/default_value_accessor';
import * as import11 from '@angular/forms/src/directives/number_value_accessor';
import * as import12 from '@angular/forms/src/directives/ng_model';
import * as import13 from '@angular/forms/src/directives/ng_control_status';
import * as import14 from '@angular/core/src/linker/element_ref';
import * as import15 from '@angular/forms/src/directives/control_value_accessor';
import * as import16 from '@angular/forms/src/directives/ng_control';
import * as import17 from '@angular/core/src/security';
var renderType_TypographyThingerComponent_Host:import0.RenderComponentType = (null as any);
class _View_TypographyThingerComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _TypographyThingerComponent_0_4:import3.TypographyThingerComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TypographyThingerComponent_Host0,renderType_TypographyThingerComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('typography-thinger',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_TypographyThingerComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TypographyThingerComponent_0_4 = new import3.TypographyThingerComponent();
    this._appEl_0.initComponent(this._TypographyThingerComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._TypographyThingerComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.TypographyThingerComponent) && (0 === requestNodeIndex))) { return this._TypographyThingerComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_TypographyThingerComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_TypographyThingerComponent_Host === (null as any))) { (renderType_TypographyThingerComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_TypographyThingerComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const TypographyThingerComponentNgFactory:import9.ComponentFactory<import3.TypographyThingerComponent> = new import9.ComponentFactory<import3.TypographyThingerComponent>('typography-thinger',viewFactory_TypographyThingerComponent_Host0,import3.TypographyThingerComponent);
const styles_TypographyThingerComponent:any[] = ([] as any[]);
var renderType_TypographyThingerComponent:import0.RenderComponentType = (null as any);
class _View_TypographyThingerComponent0 extends import1.AppView<import3.TypographyThingerComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _DefaultValueAccessor_17_3:import10.DefaultValueAccessor;
  _NumberValueAccessor_17_4:import11.NumberValueAccessor;
  _NG_VALUE_ACCESSOR_17_5:any[];
  _NgModel_17_6:import12.NgModel;
  _NgControl_17_7:any;
  _NgControlStatus_17_8:import13.NgControlStatus;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _DefaultValueAccessor_25_3:import10.DefaultValueAccessor;
  _NumberValueAccessor_25_4:import11.NumberValueAccessor;
  _NG_VALUE_ACCESSOR_25_5:any[];
  _NgModel_25_6:import12.NgModel;
  _NgControl_25_7:any;
  _NgControlStatus_25_8:import13.NgControlStatus;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _DefaultValueAccessor_33_3:import10.DefaultValueAccessor;
  _NumberValueAccessor_33_4:import11.NumberValueAccessor;
  _NG_VALUE_ACCESSOR_33_5:any[];
  _NgModel_33_6:import12.NgModel;
  _NgControl_33_7:any;
  _NgControlStatus_33_8:import13.NgControlStatus;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_49:any;
  /*private*/ _expr_50:any;
  /*private*/ _expr_51:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TypographyThingerComponent0,renderType_TypographyThingerComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','container');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','typography-thinger row');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','col-sm-2');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','card');
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','top-line-heavy');
    this._text_9 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','card-block');
    this._text_11 = this.renderer.createText(this._el_10,'\n                    ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','row');
    this._text_13 = this.renderer.createText(this._el_12,'\n                        ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'label',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','input-group col-sm-6');
    this.renderer.setElementAttribute(this._el_14,'for','font-size');
    this._text_15 = this.renderer.createText(this._el_14,'Font Size',(null as any));
    this._text_16 = this.renderer.createText(this._el_12,'\n                        ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_12,'input',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','form-control col-sm-5');
    this.renderer.setElementAttribute(this._el_17,'id','font-size');
    this.renderer.setElementAttribute(this._el_17,'type','number');
    this._DefaultValueAccessor_17_3 = new import10.DefaultValueAccessor(this.renderer,new import14.ElementRef(this._el_17));
    this._NumberValueAccessor_17_4 = new import11.NumberValueAccessor(this.renderer,new import14.ElementRef(this._el_17));
    this._NG_VALUE_ACCESSOR_17_5 = [
      this._DefaultValueAccessor_17_3,
      this._NumberValueAccessor_17_4
    ]
    ;
    this._NgModel_17_6 = new import12.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_17_5);
    this._NgControl_17_7 = this._NgModel_17_6;
    this._NgControlStatus_17_8 = new import13.NgControlStatus(this._NgControl_17_7);
    this._text_18 = this.renderer.createText(this._el_12,'\n                    ',(null as any));
    this._text_19 = this.renderer.createText(this._el_10,'\n                    ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_10,'div',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','row');
    this._text_21 = this.renderer.createText(this._el_20,'\n                        ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'label',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','input-group col-sm-6');
    this.renderer.setElementAttribute(this._el_22,'for','line-height');
    this._text_23 = this.renderer.createText(this._el_22,'Line Height',(null as any));
    this._text_24 = this.renderer.createText(this._el_20,'\n                        ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_20,'input',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','form-control col-sm-5');
    this.renderer.setElementAttribute(this._el_25,'id','line-height');
    this.renderer.setElementAttribute(this._el_25,'type','number');
    this._DefaultValueAccessor_25_3 = new import10.DefaultValueAccessor(this.renderer,new import14.ElementRef(this._el_25));
    this._NumberValueAccessor_25_4 = new import11.NumberValueAccessor(this.renderer,new import14.ElementRef(this._el_25));
    this._NG_VALUE_ACCESSOR_25_5 = [
      this._DefaultValueAccessor_25_3,
      this._NumberValueAccessor_25_4
    ]
    ;
    this._NgModel_25_6 = new import12.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_25_5);
    this._NgControl_25_7 = this._NgModel_25_6;
    this._NgControlStatus_25_8 = new import13.NgControlStatus(this._NgControl_25_7);
    this._text_26 = this.renderer.createText(this._el_20,'\n                    ',(null as any));
    this._text_27 = this.renderer.createText(this._el_10,'\n                    ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_10,'div',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','row');
    this._text_29 = this.renderer.createText(this._el_28,'\n                        ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_28,'label',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','input-group col-sm-6');
    this.renderer.setElementAttribute(this._el_30,'for','line-width');
    this._text_31 = this.renderer.createText(this._el_30,'Line Width',(null as any));
    this._text_32 = this.renderer.createText(this._el_28,'\n                        ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_28,'input',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','form-control col-sm-5');
    this.renderer.setElementAttribute(this._el_33,'id','line-width');
    this.renderer.setElementAttribute(this._el_33,'type','number');
    this._DefaultValueAccessor_33_3 = new import10.DefaultValueAccessor(this.renderer,new import14.ElementRef(this._el_33));
    this._NumberValueAccessor_33_4 = new import11.NumberValueAccessor(this.renderer,new import14.ElementRef(this._el_33));
    this._NG_VALUE_ACCESSOR_33_5 = [
      this._DefaultValueAccessor_33_3,
      this._NumberValueAccessor_33_4
    ]
    ;
    this._NgModel_33_6 = new import12.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_33_5);
    this._NgControl_33_7 = this._NgModel_33_6;
    this._NgControlStatus_33_8 = new import13.NgControlStatus(this._NgControl_33_7);
    this._text_34 = this.renderer.createText(this._el_28,'\n                    ',(null as any));
    this._text_35 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._text_36 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_37 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_38 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','col-sm-6');
    this._text_40 = this.renderer.createText(this._el_39,'\n            ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_39,'div',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','card widget-std');
    this._text_42 = this.renderer.createText(this._el_41,'\n\n                ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_41,'div',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','top-line-heavy');
    this._text_44 = this.renderer.createText(this._el_41,'\n\n                ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_41,'div',(null as any));
    this.renderer.setElementAttribute(this._el_45,'class','card-block');
    this._text_46 = this.renderer.createText(this._el_45,'\n                    ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_45,'div',(null as any));
    this.renderer.setElementAttribute(this._el_47,'class','test-area');
    this._text_48 = this.renderer.createText(this._el_47,'\n                        ',(null as any));
    this._el_49 = this.renderer.createElement(this._el_47,'p',(null as any));
    this._text_50 = this.renderer.createText(this._el_49,'\n                            The Quick Brown Fox Jumped over the Lazy Dog. But just because the dog is lazy, doesn\'t mean\n                            it\'s not a dog. The results were messy.',(null as any));
    this._text_51 = this.renderer.createText(this._el_47,'\n                        ',(null as any));
    this._el_52 = this.renderer.createElement(this._el_47,'p',(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'\n                            Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci\n                            velit,\n                            sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat\n                            voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit\n                            laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit\n                            qui\n                            in ea voluptate velit esse quam\n                        ',(null as any));
    this._text_54 = this.renderer.createText(this._el_47,'\n                        ',(null as any));
    this._el_55 = this.renderer.createElement(this._el_47,'p',(null as any));
    this._text_56 = this.renderer.createText(this._el_55,'\n                            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut\n                            labore et\n                            dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi\n                            ut\n                            aliquip\n                            ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n                            cillum\n                            dolore\n                            eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui\n                            officia\n                            deserunt mollit anim id est laborum.',(null as any));
    this._text_57 = this.renderer.createText(this._el_47,'\n                    ',(null as any));
    this._text_58 = this.renderer.createText(this._el_45,'\n                ',(null as any));
    this._text_59 = this.renderer.createText(this._el_41,'\n            ',(null as any));
    this._text_60 = this.renderer.createText(this._el_39,'\n        ',(null as any));
    this._text_61 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_62 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_17,'ngModelChange',this.eventHandler(this._handle_ngModelChange_17_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_17,'change',this.eventHandler(this._handle_change_17_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_17,'input',this.eventHandler(this._handle_input_17_2.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_17,'blur',this.eventHandler(this._handle_blur_17_3.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_17_6.update.subscribe(this.eventHandler(this._handle_ngModelChange_17_0.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_25,'ngModelChange',this.eventHandler(this._handle_ngModelChange_25_0.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_25,'change',this.eventHandler(this._handle_change_25_1.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_25,'input',this.eventHandler(this._handle_input_25_2.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_25,'blur',this.eventHandler(this._handle_blur_25_3.bind(this)));
    this._expr_21 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_25_6.update.subscribe(this.eventHandler(this._handle_ngModelChange_25_0.bind(this)));
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    var disposable_8:Function = this.renderer.listen(this._el_33,'ngModelChange',this.eventHandler(this._handle_ngModelChange_33_0.bind(this)));
    var disposable_9:Function = this.renderer.listen(this._el_33,'change',this.eventHandler(this._handle_change_33_1.bind(this)));
    var disposable_10:Function = this.renderer.listen(this._el_33,'input',this.eventHandler(this._handle_input_33_2.bind(this)));
    var disposable_11:Function = this.renderer.listen(this._el_33,'blur',this.eventHandler(this._handle_blur_33_3.bind(this)));
    this._expr_35 = import7.UNINITIALIZED;
    const subscription_2:any = this._NgModel_33_6.update.subscribe(this.eventHandler(this._handle_ngModelChange_33_0.bind(this)));
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    this._expr_41 = import7.UNINITIALIZED;
    this._expr_42 = import7.UNINITIALIZED;
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    this._expr_45 = import7.UNINITIALIZED;
    this._expr_46 = import7.UNINITIALIZED;
    this._expr_47 = import7.UNINITIALIZED;
    this._expr_48 = import7.UNINITIALIZED;
    this._expr_49 = import7.UNINITIALIZED;
    this._expr_50 = import7.UNINITIALIZED;
    this._expr_51 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._text_62
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.DefaultValueAccessor) && (17 === requestNodeIndex))) { return this._DefaultValueAccessor_17_3; }
    if (((token === import11.NumberValueAccessor) && (17 === requestNodeIndex))) { return this._NumberValueAccessor_17_4; }
    if (((token === import15.NG_VALUE_ACCESSOR) && (17 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_17_5; }
    if (((token === import12.NgModel) && (17 === requestNodeIndex))) { return this._NgModel_17_6; }
    if (((token === import16.NgControl) && (17 === requestNodeIndex))) { return this._NgControl_17_7; }
    if (((token === import13.NgControlStatus) && (17 === requestNodeIndex))) { return this._NgControlStatus_17_8; }
    if (((token === import10.DefaultValueAccessor) && (25 === requestNodeIndex))) { return this._DefaultValueAccessor_25_3; }
    if (((token === import11.NumberValueAccessor) && (25 === requestNodeIndex))) { return this._NumberValueAccessor_25_4; }
    if (((token === import15.NG_VALUE_ACCESSOR) && (25 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_25_5; }
    if (((token === import12.NgModel) && (25 === requestNodeIndex))) { return this._NgModel_25_6; }
    if (((token === import16.NgControl) && (25 === requestNodeIndex))) { return this._NgControl_25_7; }
    if (((token === import13.NgControlStatus) && (25 === requestNodeIndex))) { return this._NgControlStatus_25_8; }
    if (((token === import10.DefaultValueAccessor) && (33 === requestNodeIndex))) { return this._DefaultValueAccessor_33_3; }
    if (((token === import11.NumberValueAccessor) && (33 === requestNodeIndex))) { return this._NumberValueAccessor_33_4; }
    if (((token === import15.NG_VALUE_ACCESSOR) && (33 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_33_5; }
    if (((token === import12.NgModel) && (33 === requestNodeIndex))) { return this._NgModel_33_6; }
    if (((token === import16.NgControl) && (33 === requestNodeIndex))) { return this._NgControl_33_7; }
    if (((token === import13.NgControlStatus) && (33 === requestNodeIndex))) { return this._NgControlStatus_33_8; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_7:any = this.context.fontSize;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._NgModel_17_6.model = currVal_7;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_7,currVal_7);
      this._expr_7 = currVal_7;
    }
    if ((changes !== (null as any))) { this._NgModel_17_6.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_21:any = this.context.lineHeight;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this._NgModel_25_6.model = currVal_21;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_21,currVal_21);
      this._expr_21 = currVal_21;
    }
    if ((changes !== (null as any))) { this._NgModel_25_6.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_35:any = this.context.lineWidth;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this._NgModel_33_6.model = currVal_35;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_35,currVal_35);
      this._expr_35 = currVal_35;
    }
    if ((changes !== (null as any))) { this._NgModel_33_6.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_8:any = this._NgControlStatus_17_8.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_17,'ng-untouched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_17_8.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_17,'ng-touched',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_17_8.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_17,'ng-pristine',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_17_8.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_17,'ng-dirty',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_17_8.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_17,'ng-valid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatus_17_8.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_17,'ng-invalid',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_22:any = this._NgControlStatus_25_8.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_25,'ng-untouched',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_25_8.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_25,'ng-touched',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_25_8.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_25,'ng-pristine',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._NgControlStatus_25_8.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_25,'ng-dirty',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_25_8.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_25,'ng-valid',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_25_8.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_25,'ng-invalid',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_36:any = this._NgControlStatus_33_8.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_33,'ng-untouched',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this._NgControlStatus_33_8.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_33,'ng-touched',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = this._NgControlStatus_33_8.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_33,'ng-pristine',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_39:any = this._NgControlStatus_33_8.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementClass(this._el_33,'ng-dirty',currVal_39);
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = this._NgControlStatus_33_8.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementClass(this._el_33,'ng-valid',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_41:any = this._NgControlStatus_33_8.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this.renderer.setElementClass(this._el_33,'ng-invalid',currVal_41);
      this._expr_41 = currVal_41;
    }
    const currVal_42:any = this.context.containerSize();
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementStyle(this._el_41,'width',((this.viewUtils.sanitizer.sanitize(import17.SecurityContext.STYLE,currVal_42) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import17.SecurityContext.STYLE,currVal_42).toString()));
      this._expr_42 = currVal_42;
    }
    const currVal_43:any = (('' + this.context.lineHeight) + 'px');
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setElementStyle(this._el_49,'line-height',((this.viewUtils.sanitizer.sanitize(import17.SecurityContext.STYLE,currVal_43) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import17.SecurityContext.STYLE,currVal_43).toString()));
      this._expr_43 = currVal_43;
    }
    const currVal_44:any = this.context.fontSize;
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementStyle(this._el_49,'font-size',((this.viewUtils.sanitizer.sanitize(import17.SecurityContext.STYLE,currVal_44) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import17.SecurityContext.STYLE,currVal_44).toString()));
      this._expr_44 = currVal_44;
    }
    const currVal_45:any = this.context.lineWidth;
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementStyle(this._el_49,'width',((this.viewUtils.sanitizer.sanitize(import17.SecurityContext.STYLE,currVal_45) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import17.SecurityContext.STYLE,currVal_45).toString()));
      this._expr_45 = currVal_45;
    }
    const currVal_46:any = (('' + this.context.lineHeight) + 'px');
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementStyle(this._el_52,'line-height',((this.viewUtils.sanitizer.sanitize(import17.SecurityContext.STYLE,currVal_46) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import17.SecurityContext.STYLE,currVal_46).toString()));
      this._expr_46 = currVal_46;
    }
    const currVal_47:any = this.context.fontSize;
    if (import4.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this.renderer.setElementStyle(this._el_52,'font-size',((this.viewUtils.sanitizer.sanitize(import17.SecurityContext.STYLE,currVal_47) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import17.SecurityContext.STYLE,currVal_47).toString()));
      this._expr_47 = currVal_47;
    }
    const currVal_48:any = this.context.lineWidth;
    if (import4.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementStyle(this._el_52,'width',((this.viewUtils.sanitizer.sanitize(import17.SecurityContext.STYLE,currVal_48) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import17.SecurityContext.STYLE,currVal_48).toString()));
      this._expr_48 = currVal_48;
    }
    const currVal_49:any = (('' + this.context.lineHeight) + 'px');
    if (import4.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this.renderer.setElementStyle(this._el_55,'line-height',((this.viewUtils.sanitizer.sanitize(import17.SecurityContext.STYLE,currVal_49) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import17.SecurityContext.STYLE,currVal_49).toString()));
      this._expr_49 = currVal_49;
    }
    const currVal_50:any = this.context.fontSize;
    if (import4.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this.renderer.setElementStyle(this._el_55,'font-size',((this.viewUtils.sanitizer.sanitize(import17.SecurityContext.STYLE,currVal_50) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import17.SecurityContext.STYLE,currVal_50).toString()));
      this._expr_50 = currVal_50;
    }
    const currVal_51:any = this.context.lineWidth;
    if (import4.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this.renderer.setElementStyle(this._el_55,'width',((this.viewUtils.sanitizer.sanitize(import17.SecurityContext.STYLE,currVal_51) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import17.SecurityContext.STYLE,currVal_51).toString()));
      this._expr_51 = currVal_51;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_17_6.ngOnDestroy();
    this._NgModel_25_6.ngOnDestroy();
    this._NgModel_33_6.ngOnDestroy();
  }
  private _handle_ngModelChange_17_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.fontSize = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_change_17_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.resolveSizes('FontSize')) !== false);
    const pd_1:any = ((<any>this._NumberValueAccessor_17_4.onChange($event.target.value)) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_input_17_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_17_3.onChange($event.target.value)) !== false);
    const pd_1:any = ((<any>this._NumberValueAccessor_17_4.onChange($event.target.value)) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_blur_17_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_17_3.onTouched()) !== false);
    const pd_1:any = ((<any>this._NumberValueAccessor_17_4.onTouched()) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_ngModelChange_25_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.lineHeight = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_change_25_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.resolveSizes('LineHeight')) !== false);
    const pd_1:any = ((<any>this._NumberValueAccessor_25_4.onChange($event.target.value)) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_input_25_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_25_3.onChange($event.target.value)) !== false);
    const pd_1:any = ((<any>this._NumberValueAccessor_25_4.onChange($event.target.value)) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_blur_25_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_25_3.onTouched()) !== false);
    const pd_1:any = ((<any>this._NumberValueAccessor_25_4.onTouched()) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_ngModelChange_33_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.lineWidth = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_change_33_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.resolveSizes('LineWidth')) !== false);
    const pd_1:any = ((<any>this._NumberValueAccessor_33_4.onChange($event.target.value)) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_input_33_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_33_3.onChange($event.target.value)) !== false);
    const pd_1:any = ((<any>this._NumberValueAccessor_33_4.onChange($event.target.value)) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_blur_33_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_33_3.onTouched()) !== false);
    const pd_1:any = ((<any>this._NumberValueAccessor_33_4.onTouched()) !== false);
    return ((true && pd_0) && pd_1);
  }
}
export function viewFactory_TypographyThingerComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.TypographyThingerComponent> {
  if ((renderType_TypographyThingerComponent === (null as any))) { (renderType_TypographyThingerComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_TypographyThingerComponent,{})); }
  return new _View_TypographyThingerComponent0(viewUtils,parentInjector,declarationEl);
}