/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../app/battler/BattlerMain';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/core/src/security';
var renderType_BattlerMain_Host:import0.RenderComponentType = (null as any);
class _View_BattlerMain_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _BattlerMain_0_4:import3.BattlerMain;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_BattlerMain_Host0,renderType_BattlerMain_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_BattlerMain0(this.viewUtils,this.injector(0),this._appEl_0);
    this._BattlerMain_0_4 = new import3.BattlerMain();
    this._appEl_0.initComponent(this._BattlerMain_0_4,([] as any[]),compView_0);
    compView_0.create(this._BattlerMain_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.BattlerMain) && (0 === requestNodeIndex))) { return this._BattlerMain_0_4; }
    return notFoundResult;
  }
}
function viewFactory_BattlerMain_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_BattlerMain_Host === (null as any))) { (renderType_BattlerMain_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_BattlerMain_Host0(viewUtils,parentInjector,declarationEl);
}
export const BattlerMainNgFactory:import9.ComponentFactory<import3.BattlerMain> = new import9.ComponentFactory<import3.BattlerMain>('ng-component',viewFactory_BattlerMain_Host0,import3.BattlerMain);
const styles_BattlerMain:any[] = ([] as any[]);
var renderType_BattlerMain:import0.RenderComponentType = (null as any);
class _View_BattlerMain0 extends import1.AppView<import3.BattlerMain> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _text_53:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_BattlerMain0,renderType_BattlerMain,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','container');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','row arena');
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','col-sm-2');
    this._text_5 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','col-sm-8');
    this.renderer.setElementAttribute(this._el_6,'style','background: antiquewhite');
    this._text_7 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','opponent row');
    this._text_9 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'div',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','col-sm-5');
    this._text_11 = this.renderer.createText(this._el_10,'\n          ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','hp');
    this._text_13 = this.renderer.createText(this._el_12,'',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n          ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_10,'progress',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','progress progress-danger');
    this._text_16 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._text_17 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_8,'div',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','col-sm-3');
    this._text_19 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_8,'div',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','col-sm-3');
    this._text_21 = this.renderer.createText(this._el_20,'\n          ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','front-mon');
    this._text_23 = this.renderer.createText(this._el_22,'\n            ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'img',(null as any));
    this._text_25 = this.renderer.createText(this._el_22,'\n          ',(null as any));
    this._text_26 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._text_27 = this.renderer.createText(this._el_8,'\n      ',(null as any));
    this._text_28 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','player row');
    this._text_30 = this.renderer.createText(this._el_29,'\n        ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_29,'div',(null as any));
    this.renderer.setElementAttribute(this._el_31,'class','col-sm-3');
    this._text_32 = this.renderer.createText(this._el_31,'\n          ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_31,'div',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','back-mon');
    this._text_34 = this.renderer.createText(this._el_33,'\n            ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'img',(null as any));
    this._text_36 = this.renderer.createText(this._el_33,'\n          ',(null as any));
    this._text_37 = this.renderer.createText(this._el_31,'\n        ',(null as any));
    this._text_38 = this.renderer.createText(this._el_29,'\n        ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_29,'div',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','col-sm-3');
    this._text_40 = this.renderer.createText(this._el_29,'\n        ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_29,'div',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','col-sm-5');
    this.renderer.setElementAttribute(this._el_41,'style','align-content: center');
    this._text_42 = this.renderer.createText(this._el_41,'\n          ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_41,'div',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','hp');
    this._text_44 = this.renderer.createText(this._el_43,'',(null as any));
    this._text_45 = this.renderer.createText(this._el_41,'\n          ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_41,'progress',(null as any));
    this.renderer.setElementAttribute(this._el_46,'class','progress progress-danger');
    this._text_47 = this.renderer.createText(this._el_41,'\n        ',(null as any));
    this._text_48 = this.renderer.createText(this._el_29,'\n      ',(null as any));
    this._text_49 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._text_50 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_51,'class','col-sm-2');
    this._text_52 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_53 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(2,'HP ',this.context.arena.opponent.hp,'/',this.context.arena.opponent.max_hp,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_13,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.context.arena.opponent.hp,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_15,'value',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'',this.context.arena.opponent.max_hp,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_15,'max',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'',this.context.arena.opponent.frontImage,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_24,'src',this.viewUtils.sanitizer.sanitize(import10.SecurityContext.URL,currVal_3));
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(1,'',this.context.arena.player.backImage,'');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_35,'src',this.viewUtils.sanitizer.sanitize(import10.SecurityContext.URL,currVal_4));
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(2,'HP ',this.context.arena.player.hp,'/',this.context.arena.player.max_hp,'');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_44,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import4.interpolate(1,'',this.context.arena.player.hp,'');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementProperty(this._el_46,'value',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = import4.interpolate(1,'',this.context.arena.player.max_hp,'');
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementProperty(this._el_46,'max',currVal_7);
      this._expr_7 = currVal_7;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_BattlerMain0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.BattlerMain> {
  if ((renderType_BattlerMain === (null as any))) { (renderType_BattlerMain = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_BattlerMain,{})); }
  return new _View_BattlerMain0(viewUtils,parentInjector,declarationEl);
}