/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../app/widget/widget';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
var renderType_CardWidget_Host:import0.RenderComponentType = (null as any);
class _View_CardWidget_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _CardWidget_0_4:import3.CardWidget;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_CardWidget_Host0,renderType_CardWidget_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('card-widget',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_CardWidget0(this.viewUtils,this.injector(0),this._appEl_0);
    this._CardWidget_0_4 = new import3.CardWidget();
    this._appEl_0.initComponent(this._CardWidget_0_4,([] as any[]),compView_0);
    compView_0.create(this._CardWidget_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.CardWidget) && (0 === requestNodeIndex))) { return this._CardWidget_0_4; }
    return notFoundResult;
  }
}
function viewFactory_CardWidget_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_CardWidget_Host === (null as any))) { (renderType_CardWidget_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_CardWidget_Host0(viewUtils,parentInjector,declarationEl);
}
export const CardWidgetNgFactory:import9.ComponentFactory<import3.CardWidget> = new import9.ComponentFactory<import3.CardWidget>('card-widget',viewFactory_CardWidget_Host0,import3.CardWidget);
const styles_CardWidget:any[] = ([] as any[]);
var renderType_CardWidget:import0.RenderComponentType = (null as any);
class _View_CardWidget0 extends import1.AppView<import3.CardWidget> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_CardWidget0,renderType_CardWidget,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','card-widget card widget-std');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','top-line-heavy');
    this._text_3 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','card-block');
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this.renderer.projectNodes(this._el_4,import4.flattenNestedViewRenderNodes(this.projectableNodes[0]));
    this._text_6 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
export function viewFactory_CardWidget0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.CardWidget> {
  if ((renderType_CardWidget === (null as any))) { (renderType_CardWidget = viewUtils.createRenderComponentType('',1,import8.ViewEncapsulation.None,styles_CardWidget,{})); }
  return new _View_CardWidget0(viewUtils,parentInjector,declarationEl);
}