/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../app/app.modules';
import * as import2 from '@angular/http/src/http_module';
import * as import3 from '@angular/forms/src/directives';
import * as import4 from '@angular/forms/src/form_providers';
import * as import5 from '@angular/common/src/common_module';
import * as import6 from '@angular/core/src/application_module';
import * as import7 from '@angular/platform-browser/src/browser';
import * as import8 from '@angular/router/src/router_module';
import * as import9 from '@angular/http/src/backends/browser_xhr';
import * as import10 from '@angular/http/src/base_response_options';
import * as import11 from '@angular/http/src/backends/xhr_backend';
import * as import12 from '@angular/http/src/base_request_options';
import * as import13 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import14 from '@angular/common/src/localization';
import * as import15 from '@angular/core/src/application_init';
import * as import16 from '@angular/core/src/testability/testability';
import * as import17 from '@angular/core/src/application_ref';
import * as import18 from '@angular/core/src/linker/compiler';
import * as import19 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import20 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import21 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import22 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import23 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import24 from '@angular/core/src/linker/view_utils';
import * as import25 from '@angular/platform-browser/src/browser/title';
import * as import26 from '@angular/common/src/location/location';
import * as import27 from '@angular/router/src/url_tree';
import * as import28 from '@angular/router/src/router_outlet_map';
import * as import29 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import30 from '../../app/dataline/http-dataline';
import * as import31 from '@angular/core/src/di/injector';
import * as import32 from './home/home.ngfactory';
import * as import33 from './game-of-life/game-of-life.ngfactory';
import * as import34 from './line-height/typography-thinger.ngfactory';
import * as import35 from './dataline/DataLineComponent.ngfactory';
import * as import36 from './util/not-found.ngfactory';
import * as import37 from './forefront-root/forefront-root.ngfactory';
import * as import38 from '@angular/core/src/application_tokens';
import * as import39 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import40 from '@angular/platform-browser/src/dom/events/key_events';
import * as import41 from '@angular/core/src/zone/ng_zone';
import * as import42 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import43 from '@angular/common/src/location/platform_location';
import * as import44 from '@angular/common/src/location/location_strategy';
import * as import45 from '../../app/home/home';
import * as import46 from '../../app/game-of-life/game-of-life';
import * as import47 from '../../app/line-height/typography-thinger';
import * as import48 from '../../app/dataline/DataLineComponent';
import * as import49 from '../../app/util/not-found';
import * as import50 from '@angular/router/src/router';
import * as import51 from '@angular/core/src/console';
import * as import52 from '@angular/http/src/interfaces';
import * as import53 from '@angular/http/src/http';
import * as import54 from '@angular/core/src/i18n/tokens';
import * as import55 from '@angular/core/src/error_handler';
import * as import56 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import57 from '@angular/platform-browser/src/dom/animation_driver';
import * as import58 from '@angular/core/src/render/api';
import * as import59 from '@angular/core/src/security';
import * as import60 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import61 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import62 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import63 from '@angular/router/src/router_config_loader';
import * as import64 from '@angular/router/src/router_state';
import * as import65 from '@angular/core/src/i18n/tokens';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _HttpModule_0:import2.HttpModule;
  _InternalFormsSharedModule_1:import3.InternalFormsSharedModule;
  _FormsModule_2:import4.FormsModule;
  _CommonModule_3:import5.CommonModule;
  _ApplicationModule_4:import6.ApplicationModule;
  _BrowserModule_5:import7.BrowserModule;
  _ROUTER_FORROOT_GUARD_6:any;
  _RouterModule_7:import8.RouterModule;
  _AppModule_8:import1.AppModule;
  __BrowserXhr_9:import9.BrowserXhr;
  __ResponseOptions_10:import10.BaseResponseOptions;
  __XSRFStrategy_11:any;
  __XHRBackend_12:import11.XHRBackend;
  __RequestOptions_13:import12.BaseRequestOptions;
  __Http_14:any;
  __RadioControlRegistry_15:import13.RadioControlRegistry;
  __LOCALE_ID_16:any;
  __NgLocalization_17:import14.NgLocaleLocalization;
  _ErrorHandler_18:any;
  _ApplicationInitStatus_19:import15.ApplicationInitStatus;
  _Testability_20:import16.Testability;
  _ApplicationRef__21:import17.ApplicationRef_;
  __ApplicationRef_22:any;
  __Compiler_23:import18.Compiler;
  __APP_ID_24:any;
  __DOCUMENT_25:any;
  __HAMMER_GESTURE_CONFIG_26:import19.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_27:any[];
  __EventManager_28:import20.EventManager;
  __DomSharedStylesHost_29:import21.DomSharedStylesHost;
  __AnimationDriver_30:any;
  __DomRootRenderer_31:import22.DomRootRenderer_;
  __RootRenderer_32:any;
  __DomSanitizer_33:import23.DomSanitizerImpl;
  __Sanitizer_34:any;
  __ViewUtils_35:import24.ViewUtils;
  __IterableDiffers_36:any;
  __KeyValueDiffers_37:any;
  __SharedStylesHost_38:any;
  __Title_39:import25.Title;
  __ROUTER_CONFIGURATION_40:any;
  __LocationStrategy_41:any;
  __Location_42:import26.Location;
  __UrlSerializer_43:import27.DefaultUrlSerializer;
  __RouterOutletMap_44:import28.RouterOutletMap;
  __NgModuleFactoryLoader_45:import29.SystemJsNgModuleLoader;
  __ROUTES_46:any[];
  __Router_47:any;
  __ActivatedRoute_48:any;
  __APP_BOOTSTRAP_LISTENER_49:any[];
  __HttpDataLine_50:import30.HttpDataLine;
  __TRANSLATIONS_FORMAT_51:any;
  constructor(parent:import31.Injector) {
    super(parent,[
      import32.HomeComponentNgFactory,
      import33.GameOfLifeNgFactory,
      import34.TypographyThingerNgFactory,
      import35.DataLineComponentNgFactory,
      import36.PageNotFoundComponentNgFactory,
      import37.ForeFrontRootNgFactory
    ]
    ,[import37.ForeFrontRootNgFactory]);
  }
  get _BrowserXhr_9():import9.BrowserXhr {
    if ((this.__BrowserXhr_9 == (null as any))) { (this.__BrowserXhr_9 = new import9.BrowserXhr()); }
    return this.__BrowserXhr_9;
  }
  get _ResponseOptions_10():import10.BaseResponseOptions {
    if ((this.__ResponseOptions_10 == (null as any))) { (this.__ResponseOptions_10 = new import10.BaseResponseOptions()); }
    return this.__ResponseOptions_10;
  }
  get _XSRFStrategy_11():any {
    if ((this.__XSRFStrategy_11 == (null as any))) { (this.__XSRFStrategy_11 = import2._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_11;
  }
  get _XHRBackend_12():import11.XHRBackend {
    if ((this.__XHRBackend_12 == (null as any))) { (this.__XHRBackend_12 = new import11.XHRBackend(this._BrowserXhr_9,this._ResponseOptions_10,this._XSRFStrategy_11)); }
    return this.__XHRBackend_12;
  }
  get _RequestOptions_13():import12.BaseRequestOptions {
    if ((this.__RequestOptions_13 == (null as any))) { (this.__RequestOptions_13 = new import12.BaseRequestOptions()); }
    return this.__RequestOptions_13;
  }
  get _Http_14():any {
    if ((this.__Http_14 == (null as any))) { (this.__Http_14 = import2.httpFactory(this._XHRBackend_12,this._RequestOptions_13)); }
    return this.__Http_14;
  }
  get _RadioControlRegistry_15():import13.RadioControlRegistry {
    if ((this.__RadioControlRegistry_15 == (null as any))) { (this.__RadioControlRegistry_15 = new import13.RadioControlRegistry()); }
    return this.__RadioControlRegistry_15;
  }
  get _LOCALE_ID_16():any {
    if ((this.__LOCALE_ID_16 == (null as any))) { (this.__LOCALE_ID_16 = (null as any)); }
    return this.__LOCALE_ID_16;
  }
  get _NgLocalization_17():import14.NgLocaleLocalization {
    if ((this.__NgLocalization_17 == (null as any))) { (this.__NgLocalization_17 = new import14.NgLocaleLocalization(this._LOCALE_ID_16)); }
    return this.__NgLocalization_17;
  }
  get _ApplicationRef_22():any {
    if ((this.__ApplicationRef_22 == (null as any))) { (this.__ApplicationRef_22 = this._ApplicationRef__21); }
    return this.__ApplicationRef_22;
  }
  get _Compiler_23():import18.Compiler {
    if ((this.__Compiler_23 == (null as any))) { (this.__Compiler_23 = new import18.Compiler()); }
    return this.__Compiler_23;
  }
  get _APP_ID_24():any {
    if ((this.__APP_ID_24 == (null as any))) { (this.__APP_ID_24 = import38._appIdRandomProviderFactory()); }
    return this.__APP_ID_24;
  }
  get _DOCUMENT_25():any {
    if ((this.__DOCUMENT_25 == (null as any))) { (this.__DOCUMENT_25 = import7._document()); }
    return this.__DOCUMENT_25;
  }
  get _HAMMER_GESTURE_CONFIG_26():import19.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_26 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_26 = new import19.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_26;
  }
  get _EVENT_MANAGER_PLUGINS_27():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_27 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_27 = [
      new import39.DomEventsPlugin(),
      new import40.KeyEventsPlugin(),
      new import19.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_26)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_27;
  }
  get _EventManager_28():import20.EventManager {
    if ((this.__EventManager_28 == (null as any))) { (this.__EventManager_28 = new import20.EventManager(this._EVENT_MANAGER_PLUGINS_27,this.parent.get(import41.NgZone))); }
    return this.__EventManager_28;
  }
  get _DomSharedStylesHost_29():import21.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_29 == (null as any))) { (this.__DomSharedStylesHost_29 = new import21.DomSharedStylesHost(this._DOCUMENT_25)); }
    return this.__DomSharedStylesHost_29;
  }
  get _AnimationDriver_30():any {
    if ((this.__AnimationDriver_30 == (null as any))) { (this.__AnimationDriver_30 = import7._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_30;
  }
  get _DomRootRenderer_31():import22.DomRootRenderer_ {
    if ((this.__DomRootRenderer_31 == (null as any))) { (this.__DomRootRenderer_31 = new import22.DomRootRenderer_(this._DOCUMENT_25,this._EventManager_28,this._DomSharedStylesHost_29,this._AnimationDriver_30)); }
    return this.__DomRootRenderer_31;
  }
  get _RootRenderer_32():any {
    if ((this.__RootRenderer_32 == (null as any))) { (this.__RootRenderer_32 = import42._createConditionalRootRenderer(this._DomRootRenderer_31,this.parent.get(import42.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_32;
  }
  get _DomSanitizer_33():import23.DomSanitizerImpl {
    if ((this.__DomSanitizer_33 == (null as any))) { (this.__DomSanitizer_33 = new import23.DomSanitizerImpl()); }
    return this.__DomSanitizer_33;
  }
  get _Sanitizer_34():any {
    if ((this.__Sanitizer_34 == (null as any))) { (this.__Sanitizer_34 = this._DomSanitizer_33); }
    return this.__Sanitizer_34;
  }
  get _ViewUtils_35():import24.ViewUtils {
    if ((this.__ViewUtils_35 == (null as any))) { (this.__ViewUtils_35 = new import24.ViewUtils(this._RootRenderer_32,this._APP_ID_24,this._Sanitizer_34)); }
    return this.__ViewUtils_35;
  }
  get _IterableDiffers_36():any {
    if ((this.__IterableDiffers_36 == (null as any))) { (this.__IterableDiffers_36 = import6._iterableDiffersFactory()); }
    return this.__IterableDiffers_36;
  }
  get _KeyValueDiffers_37():any {
    if ((this.__KeyValueDiffers_37 == (null as any))) { (this.__KeyValueDiffers_37 = import6._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_37;
  }
  get _SharedStylesHost_38():any {
    if ((this.__SharedStylesHost_38 == (null as any))) { (this.__SharedStylesHost_38 = this._DomSharedStylesHost_29); }
    return this.__SharedStylesHost_38;
  }
  get _Title_39():import25.Title {
    if ((this.__Title_39 == (null as any))) { (this.__Title_39 = new import25.Title()); }
    return this.__Title_39;
  }
  get _ROUTER_CONFIGURATION_40():any {
    if ((this.__ROUTER_CONFIGURATION_40 == (null as any))) { (this.__ROUTER_CONFIGURATION_40 = {}); }
    return this.__ROUTER_CONFIGURATION_40;
  }
  get _LocationStrategy_41():any {
    if ((this.__LocationStrategy_41 == (null as any))) { (this.__LocationStrategy_41 = import8.provideLocationStrategy(this.parent.get(import43.PlatformLocation),this.parent.get(import44.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_40)); }
    return this.__LocationStrategy_41;
  }
  get _Location_42():import26.Location {
    if ((this.__Location_42 == (null as any))) { (this.__Location_42 = new import26.Location(this._LocationStrategy_41)); }
    return this.__Location_42;
  }
  get _UrlSerializer_43():import27.DefaultUrlSerializer {
    if ((this.__UrlSerializer_43 == (null as any))) { (this.__UrlSerializer_43 = new import27.DefaultUrlSerializer()); }
    return this.__UrlSerializer_43;
  }
  get _RouterOutletMap_44():import28.RouterOutletMap {
    if ((this.__RouterOutletMap_44 == (null as any))) { (this.__RouterOutletMap_44 = new import28.RouterOutletMap()); }
    return this.__RouterOutletMap_44;
  }
  get _NgModuleFactoryLoader_45():import29.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_45 == (null as any))) { (this.__NgModuleFactoryLoader_45 = new import29.SystemJsNgModuleLoader(this._Compiler_23,this.parent.get(import29.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_45;
  }
  get _ROUTES_46():any[] {
      if ((this.__ROUTES_46 == (null as any))) { (this.__ROUTES_46 = [[
        {
          path: 'home',
          component: import45.HomeComponent
        }
        ,
        {
          path: 'game-of-life',
          component: import46.GameOfLife
        }
        ,
        {
          path: 'typography',
          component: import47.TypographyThinger
        }
        ,
        {
          path: 'data-line',
          component: import48.DataLineComponent
        }
        ,
        {
          path: '',
          redirectTo: 'home',
          pathMatch: 'full'
        }
        ,
        {
          path: 'index.html',
          redirectTo: 'home',
          pathMatch: 'full'
        }
        ,
        {
          path: '**',
          component: import49.PageNotFoundComponent
        }

      ]
    ]); }
    return this.__ROUTES_46;
  }
  get _Router_47():any {
    if ((this.__Router_47 == (null as any))) { (this.__Router_47 = import8.setupRouter(this._ApplicationRef_22,this._UrlSerializer_43,this._RouterOutletMap_44,this._Location_42,this,this._NgModuleFactoryLoader_45,this._Compiler_23,this._ROUTES_46,this._ROUTER_CONFIGURATION_40)); }
    return this.__Router_47;
  }
  get _ActivatedRoute_48():any {
    if ((this.__ActivatedRoute_48 == (null as any))) { (this.__ActivatedRoute_48 = import8.rootRoute(this._Router_47)); }
    return this.__ActivatedRoute_48;
  }
  get _APP_BOOTSTRAP_LISTENER_49():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_49 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_49 = [import8.initialRouterNavigation(this._Router_47,this._ROUTER_CONFIGURATION_40)]); }
    return this.__APP_BOOTSTRAP_LISTENER_49;
  }
  get _HttpDataLine_50():import30.HttpDataLine {
    if ((this.__HttpDataLine_50 == (null as any))) { (this.__HttpDataLine_50 = new import30.HttpDataLine(this._Http_14)); }
    return this.__HttpDataLine_50;
  }
  get _TRANSLATIONS_FORMAT_51():any {
    if ((this.__TRANSLATIONS_FORMAT_51 == (null as any))) { (this.__TRANSLATIONS_FORMAT_51 = (null as any)); }
    return this.__TRANSLATIONS_FORMAT_51;
  }
  createInternal():import1.AppModule {
    this._HttpModule_0 = new import2.HttpModule();
    this._InternalFormsSharedModule_1 = new import3.InternalFormsSharedModule();
    this._FormsModule_2 = new import4.FormsModule();
    this._CommonModule_3 = new import5.CommonModule();
    this._ApplicationModule_4 = new import6.ApplicationModule();
    this._BrowserModule_5 = new import7.BrowserModule(this.parent.get(import7.BrowserModule,(null as any)));
    this._ROUTER_FORROOT_GUARD_6 = import8.provideForRootGuard(this.parent.get(import50.Router,(null as any)));
    this._RouterModule_7 = new import8.RouterModule(this._ROUTER_FORROOT_GUARD_6);
    this._AppModule_8 = new import1.AppModule();
    this._ErrorHandler_18 = import7.errorHandler();
    this._ApplicationInitStatus_19 = new import15.ApplicationInitStatus(this.parent.get(import15.APP_INITIALIZER,(null as any)));
    this._Testability_20 = new import16.Testability(this.parent.get(import41.NgZone));
    this._ApplicationRef__21 = new import17.ApplicationRef_(this.parent.get(import41.NgZone),this.parent.get(import51.Console),this,this._ErrorHandler_18,this,this._ApplicationInitStatus_19,this.parent.get(import16.TestabilityRegistry,(null as any)),this._Testability_20);
    return this._AppModule_8;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.HttpModule)) { return this._HttpModule_0; }
    if ((token === import3.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_1; }
    if ((token === import4.FormsModule)) { return this._FormsModule_2; }
    if ((token === import5.CommonModule)) { return this._CommonModule_3; }
    if ((token === import6.ApplicationModule)) { return this._ApplicationModule_4; }
    if ((token === import7.BrowserModule)) { return this._BrowserModule_5; }
    if ((token === import8.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_6; }
    if ((token === import8.RouterModule)) { return this._RouterModule_7; }
    if ((token === import1.AppModule)) { return this._AppModule_8; }
    if ((token === import9.BrowserXhr)) { return this._BrowserXhr_9; }
    if ((token === import10.ResponseOptions)) { return this._ResponseOptions_10; }
    if ((token === import52.XSRFStrategy)) { return this._XSRFStrategy_11; }
    if ((token === import11.XHRBackend)) { return this._XHRBackend_12; }
    if ((token === import12.RequestOptions)) { return this._RequestOptions_13; }
    if ((token === import53.Http)) { return this._Http_14; }
    if ((token === import13.RadioControlRegistry)) { return this._RadioControlRegistry_15; }
    if ((token === import54.LOCALE_ID)) { return this._LOCALE_ID_16; }
    if ((token === import14.NgLocalization)) { return this._NgLocalization_17; }
    if ((token === import55.ErrorHandler)) { return this._ErrorHandler_18; }
    if ((token === import15.ApplicationInitStatus)) { return this._ApplicationInitStatus_19; }
    if ((token === import16.Testability)) { return this._Testability_20; }
    if ((token === import17.ApplicationRef_)) { return this._ApplicationRef__21; }
    if ((token === import17.ApplicationRef)) { return this._ApplicationRef_22; }
    if ((token === import18.Compiler)) { return this._Compiler_23; }
    if ((token === import38.APP_ID)) { return this._APP_ID_24; }
    if ((token === import56.DOCUMENT)) { return this._DOCUMENT_25; }
    if ((token === import19.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_26; }
    if ((token === import20.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_27; }
    if ((token === import20.EventManager)) { return this._EventManager_28; }
    if ((token === import21.DomSharedStylesHost)) { return this._DomSharedStylesHost_29; }
    if ((token === import57.AnimationDriver)) { return this._AnimationDriver_30; }
    if ((token === import22.DomRootRenderer)) { return this._DomRootRenderer_31; }
    if ((token === import58.RootRenderer)) { return this._RootRenderer_32; }
    if ((token === import23.DomSanitizer)) { return this._DomSanitizer_33; }
    if ((token === import59.Sanitizer)) { return this._Sanitizer_34; }
    if ((token === import24.ViewUtils)) { return this._ViewUtils_35; }
    if ((token === import60.IterableDiffers)) { return this._IterableDiffers_36; }
    if ((token === import61.KeyValueDiffers)) { return this._KeyValueDiffers_37; }
    if ((token === import21.SharedStylesHost)) { return this._SharedStylesHost_38; }
    if ((token === import25.Title)) { return this._Title_39; }
    if ((token === import8.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_40; }
    if ((token === import44.LocationStrategy)) { return this._LocationStrategy_41; }
    if ((token === import26.Location)) { return this._Location_42; }
    if ((token === import27.UrlSerializer)) { return this._UrlSerializer_43; }
    if ((token === import28.RouterOutletMap)) { return this._RouterOutletMap_44; }
    if ((token === import62.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_45; }
    if ((token === import63.ROUTES)) { return this._ROUTES_46; }
    if ((token === import50.Router)) { return this._Router_47; }
    if ((token === import64.ActivatedRoute)) { return this._ActivatedRoute_48; }
    if ((token === import38.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_49; }
    if ((token === import30.HttpDataLine)) { return this._HttpDataLine_50; }
    if ((token === import65.TRANSLATIONS_FORMAT)) { return this._TRANSLATIONS_FORMAT_51; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__21.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);