/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../app/dynamic-forms/dynamic-form-example';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../app/dynamic-forms/FormData.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../../../app/dynamic-forms/field-input-control.service';
import * as import12 from '../../../app/dynamic-forms/dynamic-form.component';
import * as import13 from './dynamic-form.component.ngfactory';
var renderType_DynamicFormsExampleComponent_Host:import0.RenderComponentType = (null as any);
class _View_DynamicFormsExampleComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _DynamicFormsExampleComponent_0_4:import3.DynamicFormsExampleComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_DynamicFormsExampleComponent_Host0,renderType_DynamicFormsExampleComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_DynamicFormsExampleComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DynamicFormsExampleComponent_0_4 = new import3.DynamicFormsExampleComponent(this.parentInjector.get(import8.FormDataService));
    this._appEl_0.initComponent(this._DynamicFormsExampleComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._DynamicFormsExampleComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.DynamicFormsExampleComponent) && (0 === requestNodeIndex))) { return this._DynamicFormsExampleComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_DynamicFormsExampleComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_DynamicFormsExampleComponent_Host === (null as any))) { (renderType_DynamicFormsExampleComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_DynamicFormsExampleComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const DynamicFormsExampleComponentNgFactory:import10.ComponentFactory<import3.DynamicFormsExampleComponent> = new import10.ComponentFactory<import3.DynamicFormsExampleComponent>('ng-component',viewFactory_DynamicFormsExampleComponent_Host0,import3.DynamicFormsExampleComponent);
const styles_DynamicFormsExampleComponent:any[] = ([] as any[]);
var renderType_DynamicFormsExampleComponent:import0.RenderComponentType = (null as any);
class _View_DynamicFormsExampleComponent0 extends import1.AppView<import3.DynamicFormsExampleComponent> {
  _el_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import2.AppElement;
  _FieldInputControlService_1_4:import11.FieldInputControlService;
  _DynamicFormComponent_1_5:import12.DynamicFormComponent;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_DynamicFormsExampleComponent0,renderType_DynamicFormsExampleComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this._el_1 = this.renderer.createElement(this._el_0,'dynamic-form',(null as any));
    this._appEl_1 = new import2.AppElement(1,0,this,this._el_1);
    var compView_1:any = import13.viewFactory_DynamicFormComponent0(this.viewUtils,this.injector(1),this._appEl_1);
    this._FieldInputControlService_1_4 = new import11.FieldInputControlService();
    this._DynamicFormComponent_1_5 = new import12.DynamicFormComponent(this._FieldInputControlService_1_4);
    this._appEl_1.initComponent(this._DynamicFormComponent_1_5,([] as any[]),compView_1);
    compView_1.create(this._DynamicFormComponent_1_5,([] as any[]),(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._el_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.FieldInputControlService) && (1 === requestNodeIndex))) { return this._FieldInputControlService_1_4; }
    if (((token === import12.DynamicFormComponent) && (1 === requestNodeIndex))) { return this._DynamicFormComponent_1_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.fieldInputs;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._DynamicFormComponent_1_5.fieldInputs = currVal_0;
      this._expr_0 = currVal_0;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._DynamicFormComponent_1_5.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_DynamicFormsExampleComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.DynamicFormsExampleComponent> {
  if ((renderType_DynamicFormsExampleComponent === (null as any))) { (renderType_DynamicFormsExampleComponent = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_DynamicFormsExampleComponent,{})); }
  return new _View_DynamicFormsExampleComponent0(viewUtils,parentInjector,declarationEl);
}